= SmallRye GraphQL Federation Demo image:https://github.com/t1/smallrye-graphql-federation-demo/actions/workflows/maven.yml/badge.svg[link=https://github.com/t1/smallrye-graphql-federation-demo/actions/workflows/maven.yml]

This is a little demo project to show the GraphQL Federation backend support in https://github.com/smallrye/smallrye-graphql[SmallRye GraphQL].

== Parts

* `product` GraphQL backend `war`: serves the name and the description.
* `price` GraphQL backend `war`: extends the product by a price.
* `order` GraphQL backend `war`: uses products for the order items.
* `gateway` GraphQL Federation server: combines the three backends into One API.
* `printer` Quarkus GraphQL CLI client: calls the gateway to print an order with all details.

== Test & Run

Just run `mvn verify`.

But you can deploy the three `war` files to any https://jakarta.ee[Jakarta EE 10] server with https://github.com/eclipse/microprofile-graphql[MicroProfile GraphQL] support, e.g. https://www.wildfly.org/downloads/[WildFly] with the https://github.com/wildfly-extras/wildfly-graphql-feature-pack[GraphQL Feature Pack]. We use my WildFly Docker Image `rdohna/wildfly:latest` via https://github.com/t1/jee-testcontainers[JEE Testcontainers].

To start the `gateway`, run `yarn install` and `yarn start`.
