#!/bin/bash

UNAME="$(uname -sm)"
VERSION="0.76.0"

echo Running on "${UNAME}"

case "${UNAME}" in
  "Darwin arm64"*) ./router@$VERSION-darwin-arm64;;
  "Linux x86_64"*) ./router@$VERSION-linux-amd64;;
  *) echo Unsupported Platform: "${UNAME}";;
esac
