name: Java CI

on:
  push:
  pull_request:
  schedule: [ cron: '48 1 * * 5' ] # weekly: At 01:48 on Friday

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 11, 17 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --no-lockfile --cwd gateway

      - run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub install
