name: Java CI

on:
  push:
  pull_request:
  schedule: [ cron: '48 1 * * 5' ] # weekly: At 01:48 on Friday

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 17, 21 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'

      - run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub install
